# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d6b44ab9cfa2f19b0af17681883618d43b40569e60d8c2d28a8521b266427eff6d69d835e75e85df2c05c823d2589dfe9250062730da287a44cf7dcc7b5df35

test:
  secret_key_base: 19e587fd105b3895a451f952481e7e131808bf9b3e2236c15aae471afeb13276c89ff867f39db72b06f5a40f852c65a975a6a7517dbffbf4c6f467fade089dd1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
